=== Jacknes/FlyHigh/web/WEB-INF/listings.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

    <!--Defines the date as XXXX-XX-XX--> 
    <xs:simpleType name="dob">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{4}-[0-9]{2}-[0-9]{2}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!--Defines the flightType as a string and can only be either economy or business-->
    <xs:simpleType name="listingType">
        <xs:restriction base="xs:string">
            <xs:pattern value="(economy|business)"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!--Defining structure of listings.xml-->
    <xs:element name="listings">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="listing" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="userID" type="xs:string"/>
                            <xs:element name="origin" type="xs:string"/>
                            <xs:element name="destination" type="xs:string"/>
                            <xs:element name="departureDate" type="dob"/>
                            <xs:element name="returnDate" type="dob"/>
                            <xs:element name="type" type="listingType"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Jacknes/FlyHigh/web/WEB-INF/listings.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<listings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="listings.xsd">
    <listing>
        <userID>4</userID>
        <origin>Sydney</origin>
        <destination>Melbourne</destination>
        <departureDate>2017-06-02</departureDate>
        <returnDate>2017-06-27</returnDate>
        <type>economy</type>
    </listing>
</listings>
