=== Jacknes/FlyHigh/web/WEB-INF/users.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://www.w3schools.com"
xmlns="https://www.w3schools.com"
elementFormDefault="qualified">

<!--    <xs:simpleType name="email">
        <xs:restriction base="xs:string">
             <xs:pattern value="(\[a-zA-z0-9\.\_\]+)@(\[a-z\-\]+)\.(\[a-z\-\]+)((\.)\[a-z\-\]+)?"/> 
            <xs:pattern value="([a-zA-z0-9\.\_]+)@([a-z\-]+)\.([a-z\-]+)((\.)[a-z\-]+)?"/>
        </xs:restriction>
    </xs:simpleType>-->
    
    <xs:simpleType name="name">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-z]+ [a-zA-z]+"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="password">
        <xs:restriction base="xs:string">
            <xs:pattern value="/^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[a-zA-Z]).{8,}$/gm"/>
            <!--(([0-9]+)([a-zA-Z]*)).{4,}-->
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="dob">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{4}-[0-9]{2}-[0-9]{2}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="userID" type="xs:integer"/>
                            <xs:element name="email" type="xs:string"/>
                            <xs:element name="name" type="name"/>
                            <xs:element name="password" type="password"/>
                            <xs:element name="dob" type="dob"/>
                            <xs:element name="admin" type="xs:boolean"/>
                            <xs:element name="bookingID" type="xs:integer"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Jacknes/FlyHigh/build/web/WEB-INF/users.xml
<<<<<<< Updated upstream
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!--<users xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.w3schools.com users.xsd">-->
=======
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
>>>>>>> Stashed changes
<users>
    <user>
        <userID>1</userID>
        <name>Root Admin</name>
        <email>admin1@flyhigh.com</email>
        <password>password</password>
        <dob>2002-09-24</dob>
        <admin>true</admin>
        <bookingID>0</bookingID>
    </user>
    <user>
        <userID>2</userID>
        <name>John Smith</name>
        <email>customer@test.com</email>
        <password>john</password>
        <dob>1997-04-23</dob>
        <admin>false</admin>
        <bookingID>0</bookingID>
    </user>
    <user>
        <userID>3</userID>
        <name>Shasha Chai</name>
        <email>Shasha@test.com</email>
        <password>shasha</password>
        <dob>1997-10-04</dob>
        <admin>false</admin>
        <bookingID>0</bookingID>
    </user>
    <user>
        <userID>4</userID>
        <name>Jack Pascoe</name>
        <email>jack@test.com</email>
        <password>jack</password>
        <dob>1997-08-17</dob>
        <admin>false</admin>
        <bookingID>0</bookingID>
    </user>
    <user>
        <userID>5</userID>
        <name>Ryan Mccartney</name>
        <email>ryan@test.com</email>
        <password>ryan</password>
        <dob>1997-05-30</dob>
        <admin>false</admin>
        <bookingID>0</bookingID>
    </user>
    <user>
        <userID>6</userID>
        <name>Jill Smith</name>
        <email>jill@test.com</email>
        <password>jill</password>
        <dob>1997-11-05</dob>
        <admin>false</admin>
        <bookingID>0</bookingID>
    </user>
    <user>
        <userID>7</userID>
        <name>Admin Two</name>
        <email>admin2@flyhigh.com</email>
        <password>admin2</password>
        <dob>2000-07-07</dob>
        <admin>true</admin>
        <bookingID>0</bookingID>
    </user>
    <user>
        <userID>788</userID>
        <name>Test</name>
        <email>Test@gmail.com</email>
        <password>test</password>
        <dob>2017-05-16</dob>
        <admin>false</admin>
        <bookingID>0</bookingID>
    </user>
    <user>
        <userID>20</userID>
        <name>TestBooking</name>
        <email>testman</email>
        <password>test</password>
        <dob>2017-05-16</dob>
        <admin>false</admin>
        <bookingID>0</bookingID>
    </user>
    <user>
        <userID>453</userID>
        <name>BookingTest2</name>
        <email>test2</email>
        <password>test</password>
        <dob>2017-05-17</dob>
        <admin>false</admin>
        <bookingID>0</bookingID>
    </user>
    <user>
        <userID>665</userID>
        <name>test3</name>
        <email>test3</email>
        <password>test</password>
        <dob>2017-05-11</dob>
        <admin>false</admin>
        <bookingID>0</bookingID>
    </user>
    <user>
        <userID>686</userID>
        <name>testFinal</name>
        <email>testfinal</email>
        <password>test</password>
        <dob>2017-05-19</dob>
        <admin>false</admin>
        <bookingID>0</bookingID>
    </user>
    <user>
        <userID>640</userID>
        <name>Jack</name>
        <email>jacknes</email>
        <password>test</password>
        <dob>2017-05-16</dob>
        <admin>false</admin>
        <bookingID>0</bookingID>
    </user>
    <user>
        <userID>855</userID>
        <name>Shasha</name>
        <email>s.chai</email>
        <password>chai</password>
        <dob>2017-05-09</dob>
        <admin>false</admin>
        <bookingID>0</bookingID>
    </user>
    <user>
        <userID>928</userID>
        <name>Jak</name>
        <email>jack</email>
        <password>test</password>
        <dob>2017-05-15</dob>
        <admin>false</admin>
        <bookingID>0</bookingID>
    </user>
    <user>
        <userID>41</userID>
        <name>a</name>
        <email>a</email>
        <password>a</password>
        <dob>2017-05-09</dob>
        <admin>false</admin>
        <bookingID>0</bookingID>
    </user>
    <user>
        <userID>782</userID>
        <name>b</name>
        <email>b</email>
        <password>b</password>
        <dob>2017-05-03</dob>
        <admin>false</admin>
        <bookingID>0</bookingID>
    </user>
        <user>
        <userID>7</userID>
        <email>admin2@flyhigh.com</email>
        <name>Admin Two</name>
        <password>admin2</password>
        <dob>2000-07-07</dob>
        <admin>true</admin>
        <bookingID>0</bookingID>
    </user>
</users>
